import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/common/Navbar";
import Footer from "./component/common/Footer";
// ১. AuthProvider ইমপোর্ট করুন (পাথ আপনার ফোল্ডার স্ট্রাকচার অনুযায়ী দিন)
import AuthProvider from "./component/auth/AuthProvider"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ২. এখানে AuthProvider দিয়ে ভেতরের সব কিছু Wrap করে দিন */}
        <AuthProvider>
          <Navbar />
          <div className="min-h-screen">{children}</div>
          <Footer />
        </AuthProvider>

      </body>
    </html>
  );
}